//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 01:04:00 PM CEST 
//


package xmllexicon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeRel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeRel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="smaller" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="greater" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeRel")
public class TypeRel {

    @XmlAttribute
    protected String smaller;
    @XmlAttribute
    protected String greater;

    /**
     * Gets the value of the smaller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmaller() {
        return smaller;
    }

    /**
     * Sets the value of the smaller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmaller(String value) {
        this.smaller = value;
    }

    /**
     * Gets the value of the greater property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGreater() {
        return greater;
    }

    /**
     * Sets the value of the greater property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGreater(String value) {
        this.greater = value;
    }

}
