package rdf;

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.RDFNode;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Statement;
import com.hp.hpl.jena.rdf.model.StmtIterator;

public class ModelViewer
{
	private Model model;
	
	public ModelViewer(Model m)
	{
		model = m;
	}
	
	public String toDot()
	{
		String output = "/* Generated by http://github.com/wetneb/MorozParser */\ndigraph G {\n";
		StmtIterator iter = model.listStatements();
		
		while(iter.hasNext())
		{
			Statement stmt = iter.nextStatement();
			Resource subject = stmt.getSubject();
			Property property = stmt.getPredicate();
			RDFNode object = stmt.getObject();
			
			output += "\""+subject.toString() + "\" -> \"" + object.toString()+ "\"" +
					" [label=\""+property.toString()+"\"];";
		}
		
		return (output+"\n}\n");
	}
}
