
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 17 22:33:29 CEST 2013
//----------------------------------------------------

package graphexpr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 16;
  public static final int PLUS = 10;
  public static final int RPAREN = 5;
  public static final int REL = 14;
  public static final int LPAREN = 4;
  public static final int COLON = 12;
  public static final int EXPR = 19;
  public static final int SUB = 13;
  public static final int RCRO = 9;
  public static final int COMMA = 6;
  public static final int EXPL = 20;
  public static final int EOF = 0;
  public static final int OBJ = 15;
  public static final int LCRO = 8;
  public static final int SEP = 7;
  public static final int error = 1;
  public static final int STR = 17;
  public static final int NODE_FRESH = 2;
  public static final int NULL = 11;
  public static final int VAR = 18;
  public static final int NODE = 3;
}

