
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 13 23:03:03 CEST 2013
//----------------------------------------------------

package graphexpr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NODE_FRESH = 2;
  public static final int NODE = 3;
  public static final int RCRO = 13;
  public static final int RCHEV = 5;
  public static final int NULL = 15;
  public static final int PLUS = 14;
  public static final int EOF = 0;
  public static final int VAR = 7;
  public static final int SEP = 11;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int LCRO = 12;
  public static final int LCHEV = 4;
  public static final int LPAREN = 8;
  public static final int NAME = 6;
}

