
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 16 17:58:31 CEST 2013
//----------------------------------------------------

package graphexpr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RCHEV = 5;
  public static final int IDENT = 16;
  public static final int PLUS = 13;
  public static final int RPAREN = 8;
  public static final int NAME = 6;
  public static final int LCHEV = 4;
  public static final int LPAREN = 7;
  public static final int COLON = 15;
  public static final int EXPR = 18;
  public static final int RCRO = 12;
  public static final int COMMA = 9;
  public static final int EXPL = 19;
  public static final int EOF = 0;
  public static final int LCRO = 11;
  public static final int SEP = 10;
  public static final int error = 1;
  public static final int NODE_FRESH = 2;
  public static final int NULL = 14;
  public static final int VAR = 17;
  public static final int NODE = 3;
}

